"""Prompt Generator node - explicit prompt generator"""
import json
import re
from pathlib import Path
from typing import Dict, Any, Optional
from config import settings
from state import AgentState


def load_template(template_name: str) -> Dict[str, Any]:
    """Load a JSON template"""
    template_path = settings.prompt_templates_dir / f"{template_name}.json"
    if not template_path.exists():
        raise FileNotFoundError(f"Template file does not exist: {template_path}")
    with open(template_path, "r", encoding="utf-8") as f:
        return json.load(f)


def format_cell_context(cell_context: Optional[Dict[str, Any]]) -> str:
    """Format cell context information for the prompt

    Args:
        cell_context: Cell context dict, containing cell_type, context_description, etc.

    Returns:
        Formatted string
    """
    if not cell_context:
        return ""
    
    return cell_context.get("context_description", "")


def extract_dataset_info(research_summary: str) -> Dict[str, str]:
    """Extract key information from the dataset description, including channel information and data organization structure

    Args:
        research_summary: Dataset description text (generated by the LLM)

    Returns:
        A dict containing the extracted information, with new data_dimension and detailed_channel_info fields
    """
    # Default values
    dataset_description = research_summary if research_summary else "Dataset information not provided"
    
    # Import functions from the data preprocessing module
    try:
        from utils_modules.data_preprocessing import (
            detect_data_dimension_from_description,
            extract_channel_mapping_from_description
        )
        
        # Detect the data dimension
        data_dimension = detect_data_dimension_from_description(research_summary)
        
        # Extract the channel mapping
        channel_mapping = extract_channel_mapping_from_description(research_summary)
    except ImportError:
        data_dimension = "unknown"
        channel_mapping = {}
    
    # Data organization structure note (added to description)
    data_structure_note = """
    
====================
Data Organization Structure (CRITICAL)
====================
The dataset follows the following organizational structure:
- Primary files (original data): Direct files in the sample directory, such as zstack.tif, MIP.tif, image.tif, etc.
  * These are original acquired or generated image data
  * Formats may be TIFF, PNG, JPG, etc.
  * May contain complex structures such as multi-channel, 3D stacks, etc.
  
- Secondary files (derived data): Files in subdirectories under the sample directory, such as slices/*.png, segmentations/*.png, etc.
  * These are derived data processed from primary files
  * The slices directory typically contains 2D slices extracted from 3D stacks (PNG format)
  * The segmentations directory (future) will contain segmentation results
  * Other subdirectories may contain other processing results

Data path selection rules:
- Code feature extraction (code): Only use primary files (original data)
  * The image_path parameter passed points to primary files (original data)
  * Do not process files in the slices directory or other subdirectories
  * Need to select appropriate loading methods based on file format (TIFF/PNG/JPG)
  
- VLM feature extraction (vlm): Prefer secondary files (such as slices directory), if not available, use primary files
  * Typically use PNG files in the slices directory for visual analysis
  * If there is no slices directory, may use primary files

Important notes:
- When generating code, must select appropriate image loading methods based on file extension and dataset description
- Do not assume all files are TIFF format
- For TIFF files, use the tifffile library
- For PNG/JPG files, use PIL or imageio library
- Need to handle different image formats and dimensions (2D, 3D, multi-channel, etc.)
"""
    
    # Try to extract image format information from description
    dataset_image_format = "Image format information is not explicitly stated in the dataset description."
    
    # Extract channel information and data dimension information
    channel_information = ""
    data_dimension_info = ""
    
    # If the description contains format information, extract the relevant parts
    if research_summary:
        # Find keywords that may contain format information
        format_keywords = ["shape", "dimension", "format", 
                          "channel", "z-stack", "z stack", "stack", "2D", "3D"]
        
        # Find keywords for data dimension information
        dimension_keywords = ["2D", "3D", "z-stack", "z stack", "volume",
                             "multi-channel", "channel collection"]
        
        lines = research_summary.split('\n')
        format_lines = []
        channel_lines = []
        dimension_lines = []
        
        for i, line in enumerate(lines):
            # Extract format information
            if any(keyword.lower() in line.lower() for keyword in format_keywords):
                # Include context lines
                start = max(0, i - 1)
                end = min(len(lines), i + 2)
                format_lines.extend(lines[start:end])
            
            # Extract dimension information (2D/3D/multi-channel)
            if any(keyword.lower() in line.lower() for keyword in dimension_keywords):
                start = max(0, i - 1)
                end = min(len(lines), i + 2)
                dimension_lines.extend(lines[start:end])
            
            # Specifically search for channel-related information (using dynamic keywords, not hardcoded)
            try:
                from utils_modules.channel_extractor import extract_channel_keywords_from_description
                # Extract keywords from the entire description
                channel_keywords = extract_channel_keywords_from_description(research_summary)
                # Add common keywords
                channel_keywords.extend(["channel", "stain", "fluorescence"])
            except ImportError:
                # If import fails, use common keywords
                channel_keywords = ["channel", "stain", "fluorescence"]
            if any(keyword.lower() in line.lower() for keyword in channel_keywords):
                start = max(0, i - 1)
                end = min(len(lines), i + 3)
                channel_lines.extend(lines[start:end])
        
        if format_lines:
            dataset_image_format = "\n".join(format_lines[:10])  # Limit the number of lines
        else:
            # If none found, use the first few paragraphs of the entire description
            paragraphs = research_summary.split('\n\n')
            dataset_image_format = "\n\n".join(paragraphs[:2])
        
        # Build the dimension information
        if dimension_lines:
            data_dimension_info = "\n".join(dimension_lines[:10])
        else:
            # Try to extract dimension information from the entire description
            desc_lower = research_summary.lower()
            if any(kw in desc_lower for kw in ["2d", "single image"]):
                data_dimension_info = "Data dimension: 2D (single 2D image)"
            elif any(kw in desc_lower for kw in ["3d", "z-stack", "z stack", "volume"]):
                data_dimension_info = "Data dimension: 3D (3D z-stack or volume data)"
            elif any(kw in desc_lower for kw in ["multi-channel", "channel collection"]):
                data_dimension_info = "Data dimension: Multi-channel 2D data collection (multiple 2D channels)"
        
        # Build the channel information
        if channel_lines:
            channel_information = "\n".join(channel_lines[:15])  # Limit the number of lines
        else:
            # Try to extract channel mapping information from the description
            desc_lower = research_summary.lower()
            if "channel" in desc_lower:
                # Extract paragraphs containing channel information
                paragraphs = research_summary.split('\n\n')
                for para in paragraphs:
                    if any(kw in para.lower() for kw in ["channel", "w1", "w2", "w3"]):
                        channel_information = para
                        break
        
        # If dimension information was found, add it to dataset_image_format
        if data_dimension_info:
            dataset_image_format = f"{data_dimension_info}\n\n{dataset_image_format}"
    
    # Build detailed channel information (used for the VLM prompt)
    detailed_channel_info = ""
    if channel_mapping:
        detailed_channel_info = "\n====================\nDetailed Channel Mapping\n====================\n"
        detailed_channel_info += f"Data Dimension Type: {data_dimension.upper()}\n\n"
        
        if data_dimension == "2d_multichannel":
            detailed_channel_info += "**IMPORTANT**: This is a 2D multi-channel dataset. The images provided are separate grayscale slices, where each slice corresponds to a different channel (biological marker).\n\n"
            detailed_channel_info += "Channel-to-slice mapping:\n"
            for ch_idx in sorted(channel_mapping.keys()):
                ch_info = channel_mapping[ch_idx]
                marker = ch_info.get("marker", f"Channel {ch_idx}")
                detailed_channel_info += f"- **Slice {ch_idx}** (slice_{ch_idx:04d}_*.png): {marker}\n"
            detailed_channel_info += "\n**Critical**: Each slice is a separate grayscale image representing one channel. When analyzing, identify which slice corresponds to which biological marker based on the slice index.\n"
        elif data_dimension == "3d":
            detailed_channel_info += "**IMPORTANT**: This is a 3D volumetric dataset. The images provided are Z-axis slices from a 3D stack.\n"
            if channel_mapping:
                detailed_channel_info += "Channel information (if applicable):\n"
                for ch_idx in sorted(channel_mapping.keys()):
                    ch_info = channel_mapping[ch_idx]
                    marker = ch_info.get("marker", f"Channel {ch_idx}")
                    detailed_channel_info += f"- Channel {ch_idx}: {marker}\n"
            detailed_channel_info += "\nThe sequence of images represents different Z-planes through the 3D volume. Analyze the spatial distribution and patterns across the Z-axis.\n"
        else:
            if channel_mapping:
                detailed_channel_info += "Channel information:\n"
                for ch_idx in sorted(channel_mapping.keys()):
                    ch_info = channel_mapping[ch_idx]
                    marker = ch_info.get("marker", f"Channel {ch_idx}")
                    detailed_channel_info += f"- Channel {ch_idx}: {marker}\n"
    
    return {
        "dataset_description": dataset_description + data_structure_note,
        "dataset_image_format": dataset_image_format,
        "channel_information": channel_information,
        "data_dimension": data_dimension,  # New
        "detailed_channel_info": detailed_channel_info,  # New
        "channel_mapping": channel_mapping  # New
    }


def fill_template(template: str, state: AgentState) -> str:
    """Fill the template placeholders, extracting information from the dataset description"""
    research_summary = str(state.get("research_summary", ""))
    
    # Check whether to enable background knowledge during features planning (used for ablation study)
    enable_bg_knowledge_in_planning = state.get("enable_background_knowledge_in_planning", True)
    
    # Decide whether to use knowledge based on the parameter
    if enable_bg_knowledge_in_planning:
        expert_knowledge = state.get("expert_knowledge")
        deep_research = state.get("deep_research")
        rag_knowledge = state.get("rag_knowledge")
    else:
        # Disable background knowledge: set to None or empty string
        expert_knowledge = None
        deep_research = None
        rag_knowledge = None
    
    # Extract information from the dataset description
    dataset_info = extract_dataset_info(research_summary)
    
    # Build the dataset description (do not add expert knowledge here, since the template has a dedicated section)
    dataset_description = dataset_info["dataset_description"]
    
    # Build the channel information and data dimension information
    channel_info = dataset_info.get("channel_information", "")
    dimension_info = dataset_info.get("dataset_image_format", "")
    data_dimension = dataset_info.get("data_dimension", "unknown")
    detailed_channel_info = dataset_info.get("detailed_channel_info", "")
    
    # Build the channel information
    if detailed_channel_info:
        channel_information = detailed_channel_info
        # If there is specific image list information, use it to replace placeholders (e.g., slice_0000_*.png)
        image_list_description = state.get("image_list_description", "")
        if image_list_description:
            # Replace placeholders with actual file names
            image_info_list = state.get("image_info_list", [])
            if image_info_list:
                # Find and replace placeholders in detailed_channel_info
                for info in image_info_list:
                    # Replace placeholders like slice_0000_*.png
                    pattern = rf'slice_{info["index"]-1:04d}_\*\.png'
                    replacement = info["filename"]
                    channel_information = re.sub(pattern, replacement, channel_information, flags=re.IGNORECASE)
    elif channel_info:
        channel_information = f"\n====================\nChannel Information\n====================\n{channel_info}\n"
    else:
        channel_information = ""
    
    # Get the specific image list description (if it exists)
    image_list_description = state.get("image_list_description", "")
    
    # Add the data dimension note
    if data_dimension != "unknown":
        dimension_note = f"\n====================\nData Dimension Type\n====================\n"
        if data_dimension == "3d":
            dimension_note += "**Data Type**: 3D Volumetric Data (Z-stack)\n"
            dimension_note += "**Image Organization**: The images provided are 2D slices extracted along the Z-axis from a 3D volume. Each image represents a different Z-plane.\n"
            dimension_note += "**Analysis Guidance**: When evaluating features, consider the spatial distribution and patterns across the Z-axis. The sequence of images shows the progression through the 3D volume.\n"
        elif data_dimension == "2d_multichannel":
            dimension_note += "**Data Type**: 2D Multi-channel Data\n"
            dimension_note += "**Image Organization**: The images provided are separate grayscale slices, where each slice represents a different channel (biological marker). The slice index corresponds to the channel number.\n"
            dimension_note += "**Analysis Guidance**: When evaluating features, pay attention to which slice corresponds to which biological marker. Each slice is a separate grayscale image representing one channel.\n"
        else:
            dimension_note += f"**Data Type**: {data_dimension}\n"
        
        dimension_info = dimension_note + "\n" + dimension_info if dimension_info else dimension_note
    
    # Ensure dimension information is clearly passed
    if dimension_info and not any(kw in dimension_info.lower() for kw in ["2d", "3d", "multi-channel"]):
        # If dimension information is unclear, try to extract from dataset_description
        desc_lower = dataset_description.lower()
        if any(kw in desc_lower for kw in ["2d", "single image"]):
            dimension_info = "Data dimension: 2D (single 2D image)\n" + dimension_info
        elif any(kw in desc_lower for kw in ["3d", "z-stack", "z stack", "volume"]):
            dimension_info = "Data dimension: 3D (3D z-stack or volume data)\n" + dimension_info
        elif any(kw in desc_lower for kw in ["multi-channel", "channel collection"]):
            dimension_info = "Data dimension: Multi-channel 2D data collection (multiple 2D channels)\n" + dimension_info
    
    # Build baseline metrics (if available)
    baseline_rsa = state.get("baseline_rsa", "N/A")
    baseline_cca = state.get("baseline_cca", "N/A")
    baseline_score = state.get("baseline_score", "N/A")
    
    if baseline_rsa != "N/A" or baseline_cca != "N/A" or baseline_score != "N/A":
        baseline_metrics = f"- Baseline / current metrics:\n  - RSA = {baseline_rsa}\n  - CCA = {baseline_cca}\n  - Combined score = {baseline_score}\n"
    else:
        baseline_metrics = ""
    
    # Get the knowledge dependency parameter (0-1, 0=fully independent, 1=fully dependent)
    knowledge_dependency = state.get("knowledge_dependency", 0.5)
    knowledge_dependency = max(0.0, min(1.0, float(knowledge_dependency)))
    
    # Adjust the guidance wording based on the knowledge dependency
    if knowledge_dependency < 0.3:
        # Low dependency: encourage free exploration
        dependency_guidance = "\n\n**CRITICAL: Low Knowledge Dependency Mode**\nYou are in a **low knowledge dependency mode** (dependency={:.1%}). This means you should:\n- **Boldly explore** completely new feature types and measurement approaches\n- **Do NOT limit yourself** to existing knowledge or known features\n- **Innovate freely** in the feature space, even if it means departing from traditional approaches\n- **Prioritize novelty** over alignment with existing knowledge\n- Use knowledge sources as **loose inspiration** only, not strict guidelines\n".format(knowledge_dependency)
    elif knowledge_dependency > 0.7:
        # High dependency: strictly follow knowledge
        dependency_guidance = "\n\n**CRITICAL: High Knowledge Dependency Mode**\nYou are in a **high knowledge dependency mode** (dependency={:.1%}). This means you should:\n- **Strictly follow** the knowledge sources provided below\n- **Prioritize features** that align with expert knowledge, research findings, and domain understanding\n- **Avoid** generating features that contradict or ignore the provided knowledge\n- **Build upon** existing knowledge rather than exploring completely new directions\n- Use knowledge sources as **primary guidelines** for feature design\n".format(knowledge_dependency)
    else:
        # Medium dependency: balanced
        dependency_guidance = "\n\n**Knowledge Dependency Mode**\nYou are in a **balanced knowledge dependency mode** (dependency={:.1%}). Balance between:\n- Using knowledge sources as guidance for feature design\n- Exploring new feature types and approaches\n- Building on proven concepts while innovating\n".format(knowledge_dependency)
    
    # Build the knowledge source information (adjusting weight based on dependency)
    if deep_research:
        if knowledge_dependency > 0.5:
            guidance_text = f"**STRONGLY prioritize** features that align with the scientific findings and biological mechanisms described above. **Strictly follow** the visual appearance descriptions."
        elif knowledge_dependency < 0.3:
            guidance_text = f"Use these research insights as **loose inspiration only**. **Feel free to explore** beyond what is described here."
        else:
            guidance_text = f"Use these research insights to inform feature design. Prioritize features that align with the scientific findings and biological mechanisms described above."
        deep_research_info = f"\n====================\nDeep Research Insights\n====================\n{deep_research}\n\n**Guidance**: {guidance_text} Pay special attention to the visual appearance descriptions of important features, as these will guide segmentation, coding, and VLM-based feature extraction.{dependency_guidance}\n"
    else:
        deep_research_info = ""
    
    if rag_knowledge:
        if knowledge_dependency > 0.5:
            guidance_text = f"**STRONGLY prioritize** features that capture the concepts, patterns, or relationships mentioned in the knowledge base. **Strictly follow** the visual appearance descriptions."
        elif knowledge_dependency < 0.3:
            guidance_text = f"Use this retrieved knowledge as **loose inspiration only**. **Feel free to explore** beyond what is mentioned here."
        else:
            guidance_text = f"Use this retrieved knowledge to guide feature design. Consider features that capture the concepts, patterns, or relationships mentioned in the knowledge base."
        rag_knowledge_info = f"\n====================\nRAG Knowledge Base\n====================\n{rag_knowledge}\n\n**Guidance**: {guidance_text} Pay special attention to the visual appearance descriptions of important features from related research, as these will guide segmentation, coding, and VLM-based feature extraction.{dependency_guidance}\n"
    else:
        rag_knowledge_info = ""
    
    if expert_knowledge:
        if knowledge_dependency > 0.5:
            guidance_text = f"**STRONGLY prioritize** the important features and morphological indicators mentioned by domain experts. **Strictly avoid** features that experts indicate are less relevant."
        elif knowledge_dependency < 0.3:
            guidance_text = f"Use this expert knowledge as **loose inspiration only**. **Feel free to explore** beyond what experts have mentioned."
        else:
            guidance_text = f"Use this expert knowledge to prioritize features. Focus on the important features and morphological indicators mentioned by domain experts."
        expert_knowledge_info = f"\n====================\nExpert Knowledge\n====================\n{expert_knowledge}\n\n**Guidance**: {guidance_text} Avoid features that experts indicate are less relevant.{dependency_guidance}\n"
    else:
        expert_knowledge_info = ""
    
    # Prepare knowledge source information for the code_generation template (slightly different format)
    if deep_research:
        deep_research_info_code = f"\n====================\nDeep Research Insights\n====================\n{deep_research}\n\n**Guidance**: Use these research insights to guide code implementation. Pay special attention to the visual appearance descriptions of important features, as these will guide how to detect and quantify features in code.\n"
    else:
        deep_research_info_code = ""
    
    if rag_knowledge:
        rag_knowledge_info_code = f"\n====================\nRAG Knowledge Base\n====================\n{rag_knowledge}\n\n**Guidance**: Use this retrieved knowledge to guide code implementation. Consider the visual appearance descriptions of important features from related research when writing detection and quantification logic.\n"
    else:
        rag_knowledge_info_code = ""
    
    if expert_knowledge:
        expert_knowledge_info_code = f"\n====================\nExpert Knowledge\n====================\n{expert_knowledge}\n\n**Guidance**: Use this expert knowledge to guide code implementation. Focus on implementing features that match the visual descriptions provided by domain experts.\n"
    else:
        expert_knowledge_info_code = ""
    
    # Build sample path information (for features that require segmentation)
    sample_paths_info = state.get("sample_paths_info", {})
    if sample_paths_info:
        paths_info_text = "\n====================\nSample Paths Information (for Segmentation Features)\n====================\n"
        paths_info_text += "**IMPORTANT**: This feature requires segmentation. Below are the relative paths for each sample:\n\n"
        paths_info_text += "For each sample, you have access to:\n"
        paths_info_text += "- Image path (relative to data_root): The primary image file for this sample\n"
        paths_info_text += "- Segmentation mask path (relative to data_root): The segmentation result file\n\n"
        paths_info_text += "Sample paths (relative to data_root):\n"
        for sample_id, paths in list(sample_paths_info.items())[:10]:  # Only show the first 10 samples
            paths_info_text += f"- Sample '{sample_id}':\n"
            paths_info_text += f"  - Image: {paths['image_path']}\n"
            paths_info_text += f"  - Segmentation mask: {paths['segmentation_mask_path']}\n"
        if len(sample_paths_info) > 10:
            paths_info_text += f"\n... and {len(sample_paths_info) - 10} more samples with similar structure.\n"
        paths_info_text += "\n**Note**: When implementing the feature, you can use these paths to understand the data structure. "
        paths_info_text += "The segmentation mask will be automatically loaded and passed as the second argument to your function if available.\n"
    else:
        paths_info_text = ""
    
    # Build the analysis results summary (for multi-round execution)
    previous_analysis_summary = state.get("previous_analysis_summary")
    analysis_guidance = ""

    # Validation Design Spec: injected only when deterministic feature validation (with-validation) is enabled,
    # so the planner can design features that pass the paired-metadata screen.
    validation_spec = ""
    if state.get("enable_feature_analysis"):
        validation_spec = (
            "## Validation Design Spec (features will be deterministically validated)\n"
            "Every feature you propose will be extracted and then screened by a deterministic validator. "
            "Features that fail ANY of the following criteria are DROPPED, so design features that are built to pass:\n"
            "- **Paired-metadata alignment (loose screen)**: when a metadata CSV is provided, each feature is checked "
            "against paired sample metadata (group / genotype / continuous covariates — NOT a transcriptome assay). "
            "Choose the metric by metadata type: use |Spearman| for continuous covariates; for categorical labels "
            "(e.g. WT/MU group or genotype) use classifier AUC as the primary criterion (eta² / ANOVA are also computed). "
            "The screen is intentionally loose: only features with essentially no metadata-tracking ability are dropped "
            "(alignment score < 0.05 and classifier AUC < 0.55). "
            "Prefer features whose biology is expected to differ across metadata groups or track continuous covariates.\n"
            "- **Coverage**: availability rate must be >= 0.70 (the feature must be computable on at least 70% of samples). "
            "Avoid features that frequently yield NaN/None or require masks that are often missing.\n"
            "- **Variability**: variability signal (CV or robust dispersion) must be >= 0.10. Avoid near-constant features.\n"
            "- **Distinct values**: at least 5 distinct valid values across samples. Avoid quasi-binary or saturated features.\n"
            "- **Non-redundancy**: a feature is treated as a duplicate and dropped if |correlation| with any existing/retained "
            "feature is >= 0.98 (ambiguous at >= 0.95 or high semantic-name overlap, then adjudicated). "
            "Make each new feature measure a genuinely different aspect; do not re-propose near-duplicates with cosmetic renaming.\n"
            "- **Composite score gate**: a base validation score combining coverage (0.45), variability (0.35) and "
            "paired-metadata alignment (0.20) must be >= 0.35.\n"
            "**Design imperative**: prioritize features that (a) are robustly computable on most samples, (b) have meaningful "
            "biological variability, (c) show at least slight alignment with paired metadata, and (d) are complementary "
            "(low correlation) to already-retained features.\n"
        )

    if previous_analysis_summary:
        prev_summary = previous_analysis_summary.get("previous_features_summary")
        if prev_summary and isinstance(prev_summary, dict):
            # Build the analysis guidance text
            analysis_guidance_parts = []
            planner_feedback = prev_summary.get("planner_feedback", {}) or {}
            validation_summary = (
                prev_summary.get("validation_summary")
                or prev_summary.get("analysis_summary")
                or {}
            )
            
            # 1. Retained/dropped/redundancy-adjudication feedback
            retained_features = planner_feedback.get("retained_features", [])
            dropped_features = planner_feedback.get("dropped_features", [])
            redundancy_resolutions = planner_feedback.get("redundancy_resolutions", [])
            top_reason_codes = planner_feedback.get("top_reason_codes", [])

            if retained_features:
                retained_names = [item.get("name", "") for item in retained_features[:10] if item.get("name")]
                if retained_names:
                    analysis_guidance_parts.append(
                        f"**Retained Features From Previous Round** (validated useful patterns):\n{', '.join(retained_names)}"
                    )
                    analysis_guidance_parts.append(
                        "\n**Critical Guidance**: Build related but distinct feature families around the retained features above. Reuse the biological concept, but change the measurement perspective, scale, or mathematical formulation."
                    )

            if dropped_features:
                dropped_preview = []
                for item in dropped_features[:10]:
                    name = item.get("name", "")
                    reasons = item.get("reasons", [])
                    if name:
                        reason_text = ", ".join(reasons[:2]) if reasons else "dropped"
                        dropped_preview.append(f"{name} ({reason_text})")
                if dropped_preview:
                    analysis_guidance_parts.append(
                        f"**Dropped Features From Previous Round** (avoid repeating these weak patterns):\n{'; '.join(dropped_preview)}"
                    )
                    analysis_guidance_parts.append(
                        "\n**Guidance**: Avoid proposing features with the same failure modes. In particular: "
                        "`low_paired_metadata_alignment` means the feature showed essentially no ability to track paired "
                        "sample metadata (group/genotype/covariates) under a loose Spearman (continuous) / "
                        "AUC (categorical) screen "
                        "-- redesign so the measurement differs across metadata groups or tracks a continuous covariate; "
                        "`low_validation_score` means weak combined coverage/variability/alignment; "
                        "`low_availability`/`low_unique_values`/`low_unsupervised_variability` mean the feature was rarely computable, "
                        "near-constant, or quasi-binary; redundancy reasons mean it duplicated an existing feature."
                    )
                    analysis_guidance_parts.append(
                        "\n**Priority for NEW features**: prefer features that show at least slight paired-metadata "
                        "alignment (AUC for categorical labels like WT/MU; Spearman for continuous covariates) "
                        "AND are complementary (low correlation) to the already-retained features above."
                    )

            if redundancy_resolutions:
                resolution_preview = []
                for item in redundancy_resolutions[:5]:
                    kept = item.get("kept_feature_ids", [])
                    dropped = item.get("dropped_feature_ids", [])
                    decision = item.get("decision", "resolved")
                    resolution_preview.append(
                        f"- {decision}: keep {', '.join(kept[:2]) if kept else 'N/A'}; drop {', '.join(dropped[:2]) if dropped else 'none'}"
                    )
                analysis_guidance_parts.append(
                    "**Redundancy Resolutions** (similar features were already adjudicated):\n" + "\n".join(resolution_preview)
                )
                analysis_guidance_parts.append(
                    "\n**Guidance**: If you extend an existing concept, make the complementarity explicit. Do not re-propose near-duplicates with only cosmetic renaming."
                )

            if top_reason_codes:
                formatted_reasons = []
                for item in top_reason_codes[:5]:
                    if isinstance(item, (list, tuple)) and len(item) >= 2:
                        formatted_reasons.append(f"{item[0]} x{item[1]}")
                if formatted_reasons:
                    analysis_guidance_parts.append(
                        f"**Most Common Rejection Reasons**:\n{', '.join(formatted_reasons)}"
                    )

            top_retained = validation_summary.get("top_retained_features", [])
            if top_retained:
                preview = [
                    f"- {item.get('feature_name', 'unknown')} (score={item.get('validation_score', 0):.3f})"
                    for item in top_retained[:5]
                ]
                analysis_guidance_parts.append(
                    "**Top Validated Features**:\n" + "\n".join(preview)
                )
            
            # 2. Feature extraction results summary
            if prev_summary.get("round"):
                analysis_guidance_parts.append(f"\n**Previous Round (Round {prev_summary['round']}) Feature Extraction Results**:")
                analysis_guidance_parts.append(f"- Extracted {prev_summary.get('features_extracted', 0)} features")
                analysis_guidance_parts.append(f"- Feature names: {', '.join(prev_summary.get('feature_names', [])[:10])}")
                analysis_guidance_parts.append(f"- Current cumulative feature count: {prev_summary.get('total_features_so_far', 0)}")
            
            # 3. Guide generation of new feature types
            # Prioritize using all existing feature names (complete list from CSV)
            all_existing = (
                planner_feedback.get("all_historical_feature_names", [])
                or prev_summary.get("all_historical_feature_names", [])
                or previous_analysis_summary.get("all_existing_feature_names", [])
            )
            if all_existing:
                existing_features = all_existing
                analysis_guidance_parts.append(f"\n**All Previously Extracted Features** (MUST avoid duplicate feature names):\n{', '.join(existing_features)}")
                analysis_guidance_parts.append(f"\n**CRITICAL Guidance for Generating NEW Features**:")
                analysis_guidance_parts.append(f"- The above {len(existing_features)} features have already been extracted. **You MUST generate features with completely different names and approaches**")
                analysis_guidance_parts.append(f"- **STRONG ENCOURAGEMENT FOR EXPLORATION**: Boldly explore completely new feature types and measurement approaches that are NOT in the list above")
                analysis_guidance_parts.append(f"- **Generate NEW Features**: Even if a feature concept seems similar, generate it with a different name, different measurement approach, or different perspective")
                analysis_guidance_parts.append(f"- **Build on High-Performing Features**: If certain features performed excellently (see the high-performing features list above), strongly recommend generating **related but distinct** new features that measure the same biological concepts from different perspectives, with different names")
                analysis_guidance_parts.append(f"- **Balance**: Both explore completely new areas AND expand on proven high-performing features to create feature families, but always with NEW feature names")
                analysis_guidance_parts.append(f"- **IMPORTANT**: The goal is to generate NEW features that complement existing ones, not to repeat what has already been done")
            elif prev_summary.get("feature_names"):
                existing_features = prev_summary["feature_names"]
                analysis_guidance_parts.append(f"\n**Previously Extracted Feature Types** (avoid duplication):\n{', '.join(existing_features[:15])}")
                analysis_guidance_parts.append("\n**Guidance**: Please generate new features that are **complementary** to the above features, focusing on aspects not well-covered by the current feature set. At the same time, if certain features performed excellently, encourage generating related new features based on them.")
            
            analysis_guidance = "\n".join(analysis_guidance_parts)

    # Place the Validation Design Spec at the very front (inject it even in the first round, when there is no historical feedback)
    if validation_spec:
        analysis_guidance = (
            validation_spec + "\n" + analysis_guidance if analysis_guidance else validation_spec
        )

    # Process the batch feature list (used for VLM batch scoring)
    features_list = state.get("features_list", [])
    num_features = state.get("num_features", len(features_list) if features_list else 0)
    features_list_text = ""
    if features_list:
        features_list_text = "\n".join([
            f"- Feature {i+1}: {feat.get('name', 'unknown')}\n  Description: {feat.get('description', 'N/A')}\n  Category: {feat.get('category', 'N/A')}"
            for i, feat in enumerate(features_list)
        ])
    else:
        features_list_text = "No features specified."
    
    # Build the fill data
    fill_data = {
        # User query and sample information
        "user_query": str(state.get("user_query", "")),
        "sample_id": str(state.get("sample_id", "")),
        "image_paths": "\n".join(state.get("image_paths", [])),
        "num_images": str(len(state.get("image_paths", []))),
        
        # Dataset information (extracted from the description)
        "dataset_description": dataset_description,
        "channel_information": channel_information,
        "dataset_image_format": dataset_info["dataset_image_format"],
        
        # Specific image list description (extracted from the actual file names)
        "image_list_description": image_list_description if image_list_description else "",
        
        # Baseline metrics (optional)
        "baseline_metrics": baseline_metrics,
        
        # Knowledge source information (for feature_planning)
        "deep_research_info": deep_research_info,
        "rag_knowledge_info": rag_knowledge_info,
        "expert_knowledge_info": expert_knowledge_info,
        
        # Knowledge source information (for code_generation, slightly different format)
        "deep_research_info_code": deep_research_info_code,
        "rag_knowledge_info_code": rag_knowledge_info_code,
        "expert_knowledge_info_code": expert_knowledge_info_code,
        
        # Feature planning related (if it exists)
        "hq_count": str(state.get("hq_count", "0")),
        "target_feature_count": str(settings.target_feature_count),
        "top_features": str(state.get("top_features", "None (first iteration)")),
        "category_distribution": str(state.get("category_distribution", "Not available")),
        "previous_features": str(state.get("previous_features", "None (first iteration)")),
        "underrepresented": str(state.get("underrepresented", "Not specified")),
        "external_requirements": str(state.get("external_requirements", "None")),
        "features_per_iteration": str(settings.features_per_iteration),
        "available_methods": str(state.get("available_methods", "code, vlm")),
        "method_instructions": str(state.get("method_instructions", "None")),
        # Cell context information
        "cell_context_info": format_cell_context(state.get("cell_context")),
        
        # Multi-round execution related: analysis results guidance
        "previous_analysis_guidance": analysis_guidance if analysis_guidance else "This is the first round of feature extraction. No previous analysis results are available.",
        
        # Code generation related (if it exists)
        "feature_name": str(state.get("feature_name", "")),
        "feature_description": str(state.get("feature_description", "")),
        "feature_category": str(state.get("feature_category", "")),
        "feature_guidance_message": str(state.get("feature_guidance_message", "")),
        "seg_keys_description": str(state.get("seg_keys_description", "No segmentation. Use def extract(img): only.")),
        "segmentation_files_info": str(state.get("segmentation_files_info", "")),
        "segmentation_mask_order": str(state.get("segmentation_mask_order", "")),
        "segmentation_statistics": str(state.get("segmentation_statistics", "")),
        "image_shape": str(state.get("image_shape", "Unknown")),
        "image_dtype": str(state.get("image_dtype", "Unknown")),
        "image_min": str(state.get("image_min", "Unknown")),
        "image_max": str(state.get("image_max", "Unknown")),
        # Cell context information (for code generation)
        "cell_context_info": format_cell_context(state.get("cell_context")),
        
        # VLM scoring related (if it exists)
        # Use the same placeholder names as code generation
        # Note: the vlm_scoring template uses feature_name, feature_description, feature_category
        
        # VLM batch scoring related (if it exists)
        "features_list": features_list,  # Original list (for internal processing)
        "num_features": str(num_features),
        "features_list_text": features_list_text,
        
        # Keep legacy fields for compatibility (if still used in the template)
        "research_summary": research_summary,
        "expert_examples_text": str(state.get("expert_examples_text", "No expert examples available.")),
        "previous_results": str(state.get("previous_results", "No previous results")),
        "cell_type": "unknown",  # Extracted from the dataset description; default value kept here
        "microscopy_modality": "unknown",  # Extracted from the dataset description; default value kept here
        "input_description": research_summary[:500] if research_summary else "Dataset information not available",
        # Keep baseline metric fields (even though they may not be used in the template)
        "baseline_rsa": str(baseline_rsa),
        "baseline_cca": str(baseline_cca),
        "baseline_score": str(baseline_score),
        
        # Round information
        "round_number": str(state.get("round_number", "1")),
        
        # Sample path information (for features that require segmentation)
        "sample_paths_info": paths_info_text,
    }
    
    # Convert to strings and fill
    fill_data_str = {k: str(v) if not isinstance(v, str) else v for k, v in fill_data.items()}
    
    try:
        filled = template.format(**fill_data_str)
    except (KeyError, ValueError) as e:
        # Use regular expressions to replace the remaining placeholders
        # Note: special characters in the replacement values need to be handled correctly
        filled = template
        for key, value in fill_data_str.items():
            # Use a lambda function to avoid escaping issues
            # This safely handles values containing backslashes, quotes, and other special characters
            pattern = r'\{' + re.escape(key) + r'\}'
            # Escape backslashes in the replacement value to avoid regex parsing errors
            replacement = str(value).replace('\\', '\\\\')
            filled = re.sub(pattern, replacement, filled)
    
    return filled


def prompt_gen_node(state: AgentState) -> Dict[str, Any]:
    """Generate the filled prompt"""
    template_dict = load_template("feature_planning")
    template_str = template_dict.get("template", "")
    filled_template = fill_template(template_str, state)
    
    return {
        "feature_plan": {
            "template_filled": filled_template,
            "template_name": "feature_planning",
        },
        "current_step": "prompt_gen",
    }
