"""Reproducibility helpers for MorphAgent (--reproduce mode)."""
from __future__ import annotations

import hashlib
import json
import os
import random
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def apply_reproduce_mode(seed: int = 42) -> None:
    """Fix Python / NumPy / PyTorch RNG and CUDA flags for deterministic runs."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    try:
        import numpy as np
        np.random.seed(seed)
    except ImportError:
        pass
    try:
        import torch
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False
            os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
            try:
                torch.use_deterministic_algorithms(True, warn_only=True)
            except Exception:
                pass
    except ImportError:
        pass


def _file_fingerprint(path: str) -> str:
    """Stable fingerprint for a source image.

    Uses <sample_dir>/<basename>:<size> so the key is invariant across
    independent runs (the raw slice PNGs never change), and does NOT depend
    on per-run temp directories or mtimes. Including the parent directory name
    disambiguates identically named slices from different samples.
    """
    p = Path(path)
    try:
        size = p.stat().st_size
    except OSError:
        size = -1
    # Use up to the last 3 path components (e.g. <sample>/slices/<file>) so the
    # key identifies the sample unambiguously while staying invariant across
    # runs and independent of any temp/preprocess directory prefix.
    parts = p.parts[-3:]
    rel = "/".join(parts)
    return f"{rel}:{size}"


def vlm_cache_key(
    *,
    mode: str,
    feature_names: List[str],
    image_paths: List[str],
    prompt: str,  # kept for signature compatibility; intentionally NOT hashed
    model: str,
    provider: str,
) -> str:
    """Deterministic VLM cache key.

    The key depends only on stable inputs: the scoring mode, the feature
    name(s), the identity of the source images, and the model/provider.
    The prompt is deliberately excluded because knowledge summaries embedded
    in it are re-generated by the LLM every run; including them would make the
    key change across runs and defeat cross-run reproducibility.
    """
    payload = {
        "mode": mode,
        "features": sorted(feature_names),
        "images": sorted(_file_fingerprint(p) for p in image_paths),
        "model": model,
        "provider": provider,
    }
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _cache_file(cache_dir: str, key: str) -> Path:
    return Path(cache_dir) / f"{key}.json"


def vlm_cache_get(cache_dir: Optional[str], key: str) -> Optional[Tuple[float, str, Optional[Dict[str, float]]]]:
    """Return cached (score, response, batch_scores) or None."""
    if not cache_dir:
        return None
    path = _cache_file(cache_dir, key)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return (
            float(data["score"]),
            str(data.get("response", "")),
            data.get("batch_scores"),
        )
    except Exception:
        return None


def vlm_cache_set(
    cache_dir: Optional[str],
    key: str,
    *,
    score: float,
    response: str,
    batch_scores: Optional[Dict[str, float]] = None,
) -> None:
    if not cache_dir:
        return
    path = _cache_file(cache_dir, key)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload: Dict[str, Any] = {"score": score, "response": response}
    if batch_scores is not None:
        payload["batch_scores"] = batch_scores
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
