def extract(img, *segmentation_masks):
    # IMPORT ALL REQUIRED PACKAGES AT THE BEGINNING OF THE FUNCTION
    import numpy as np
    from scipy import ndimage
    from skimage.measure import label
    from skimage.filters import threshold_otsu
    from skimage.morphology import remove_small_objects, binary_opening, disk
    from skimage.feature import peak_local_max
    from skimage.segmentation import watershed

    # 1. Check if valid segmentation masks are provided
    # If masks are available, we prioritize using them as they are likely curated or generated by a specialized model.
    if segmentation_masks and len(segmentation_masks) > 0:
        # We assume the masks are passed. We need to find a suitable one.
        # Usually, if multiple masks exist, one might be nuclei and one cytoplasm.
        # Nuclei masks typically have more distinct objects than cytoplasm masks (which might merge).
        # However, for a simple count, we can check the first mask or iterate to find the one with the most objects.
        
        best_count = 0.0
        
        for mask in segmentation_masks:
            if mask is None:
                continue
            
            # Ensure mask is an integer array
            mask_int = mask.astype(int)
            
            # If the mask is binary (0 and 1), we need to label it to count objects
            if mask_int.max() <= 1:
                labeled_mask, num_features = label(mask_int, return_num=True)
                count = float(num_features)
            else:
                # If it's an instance segmentation (labels > 1), count unique non-zero labels
                # Optimization: assuming labels are roughly sequential, max() is a good proxy, 
                # but len(unique) is safer if labels are not contiguous.
                # label() function re-indexes them sequentially, so it's a robust way to count.
                _, num_features = label(mask_int, return_num=True)
                count = float(num_features)
            
            # Heuristic: The mask with the highest count is likely the nuclei mask (or the best separation)
            if count > best_count:
                best_count = count
                
        if best_count > 0:
            return best_count

    # 2. Fallback: Compute cell count from the raw image (Channel 2 - DAPI)
    # If no masks are provided, we perform on-the-fly segmentation on the DAPI channel.
    
    # Convert to appropriate array type
    arr = np.asarray(img, dtype=np.float32)

    # Handle dimensionality
    # Expected shape: (512, 512, 3)
    if arr.ndim == 3 and arr.shape[2] == 3:
        # Extract DAPI channel (Channel 2 / Blue)
        dapi = arr[:, :, 2]
    elif arr.ndim == 2:
        # If single channel, assume it's the relevant one
        dapi = arr
    else:
        # Unexpected shape, return 0
        return 0.0

    # Normalize DAPI channel for processing
    # Robust min-max normalization
    p_min, p_max = np.percentile(dapi, (1, 99))
    if p_max > p_min:
        dapi = (dapi - p_min) / (p_max - p_min)
    else:
        dapi = dapi - p_min
    dapi = np.clip(dapi, 0, 1)

    # Pre-processing: Gaussian blur to smooth noise
    dapi_smooth = ndimage.gaussian_filter(dapi, sigma=2)

    try:
        # Thresholding
        thresh_val = threshold_otsu(dapi_smooth)
        binary_mask = dapi_smooth > thresh_val
    except ValueError:
        # This happens if the image is completely uniform (e.g., all black)
        return 0.0

    # Morphological cleanup
    # Remove small noise specks
    binary_mask = remove_small_objects(binary_mask, min_size=30)
    # Separate touching nuclei using Watershed
    # 1. Compute distance transform
    distance = ndimage.distance_transform_edt(binary_mask)
    
    # 2. Find peaks in the distance map (centers of nuclei)
    # min_distance ensures we don't over-segment a single nucleus
    coords = peak_local_max(distance, min_distance=7, labels=binary_mask)
    mask_peaks = np.zeros(distance.shape, dtype=bool)
    mask_peaks[tuple(coords.T)] = True
    markers, _ = label(mask_peaks, return_num=True)

    # 3. Apply watershed
    labels = watershed(-distance, markers, mask=binary_mask)

    # Count the resulting labels
    # labels are 1-based integers, 0 is background
    count = float(labels.max())

    return count
