"""AgentState definition - state supporting the full workflow"""
from typing import TypedDict, List, Dict, Optional, Any, Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """State definition for MorphAgent

    Contains conversation history, context information, knowledge layer, plan, and execution results
    """
    # ========== Conversation history ==========
    messages: Annotated[List[BaseMessage], add_messages]
    
    # ========== User context ==========
    user_query: str  # The user's original query (e.g., "Quantify mitochondrial fragmentation")
    sample_id: str  # ID of the sample currently being analyzed
    image_paths: List[str]  # List of 3D z-stack slice paths
    
    # ========== Knowledge & Strategy ==========
    research_summary: str  # Summary of relevant knowledge retrieved from papers
    expert_examples: List[Dict[str, Any]]  # Expert-annotated reference image/text pairs
    expert_knowledge: Optional[str]  # Expert knowledge summary extracted from the expert_knowledge folder
    deep_research: Optional[str]  # Auxiliary information from Deep research
    rag_knowledge: Optional[str]  # Auxiliary information from RAG
    # expert_examples format: [
    #   {
    #     "image_path": "path/to/image.tif",
    #     "description": "expert annotation text",
    #     "feature_value": 85.5,  # Optional: known feature value
    #     "metadata": {...}  # Other metadata
    #   },
    #   ...
    # ]
    
    # ========== Plan layer ==========
    feature_plan: Optional[Dict[str, Any]]  # Structured plan generated by the PromptGenerator
    # feature_plan format: {
    #   "features": [
    #     {
    #       "name": "mitochondrial_fragmentation_score",
    #       "description": "...",
    #       "category": "morphology",
    #       "method": "vlm",  # "code" or "vlm"
    #       "method_rationale": "..."
    #     },
    #     ...
    #   ],
    #   "strategy": "...",  # Overall strategy description
    #   "template_filled": {...}  # Filled template content
    # }
    
    # ========== Execution layer data ==========
    segmentation_mask: Optional[Any]  # Segmentation mask (path or array), None if not used
    analysis_results: Dict[str, Any]  # Dictionary of analysis results
    # analysis_results format: {
    #   "mitochondria_count": 150,
    #   "vlm_frag_score": 85.5,
    #   "code_intensity_mean": 1234.56,
    #   ...
    # }
    
    # ========== Metadata ==========
    current_step: str  # Current workflow step: "research" | "planning" | "execution" | "synthesis"
    iteration_count: int  # Current iteration count
    error_log: List[str]  # Error log
    
    # ========== Cell context (optional) ==========
    cell_context: Optional[Dict[str, Any]]  # Cell context information: {"cell_type": "single"|"multiple"|"unknown", "context_description": str, ...}
    previous_analysis_summary: Optional[Dict[str, Any]]  # Multi-round feature planning feedback (previous round validation summary)
    round_number: int  # Current round number
    available_methods: str  # Methods allowed in the current round
    method_instructions: str  # Method restriction hint
    enable_feature_analysis: bool  # Whether to enable deterministic feature validation (used to inject the Validation Design Spec)
